VALID_FLORES_CODES = {
    'ace_Arab',
    'ace_Latn',
    'acm_Arab',
    'acq_Arab',
    'aeb_Arab',
    'afr_Latn',
    'ajp_Arab',
    'aka_Latn',
    'als_Latn',
    'amh_Ethi',
    'apc_Arab',
    'arb_Arab',
    'arb_Latn',
    'ars_Arab',
    'ary_Arab',
    'arz_Arab',
    'asm_Beng',
    'ast_Latn',
    'awa_Deva',
    'ayr_Latn',
    'azb_Arab',
    'azj_Latn',
    'bak_Cyrl',
    'bam_Latn',
    'ban_Latn',
    'bel_Cyrl',
    'bem_Latn',
    'ben_Beng',
    'bho_Deva',
    'bjn_Arab',
    'bjn_Latn',
    'bod_Tibt',
    'bos_Latn',
    'bug_Latn',
    'bul_Cyrl',
    'cat_Latn',
    'ceb_Latn',
    'ces_Latn',
    'cjk_Latn',
    'ckb_Arab',
    'crh_Latn',
    'cym_Latn',
    'dan_Latn',
    'deu_Latn',
    'dik_Latn',
    'dyu_Latn',
    'dzo_Tibt',
    'ell_Grek',
    'eng_Latn',
    'epo_Latn',
    'est_Latn',
    'eus_Latn',
    'ewe_Latn',
    'fao_Latn',
    'fij_Latn',
    'fin_Latn',
    'fon_Latn',
    'fra_Latn',
    'fur_Latn',
    'fuv_Latn',
    'gaz_Latn',
    'gla_Latn',
    'gle_Latn',
    'glg_Latn',
    'grn_Latn',
    'guj_Gujr',
    'hat_Latn',
    'hau_Latn',
    'heb_Hebr',
    'hin_Deva',
    'hne_Deva',
    'hrv_Latn',
    'hun_Latn',
    'hye_Armn',
    'ibo_Latn',
    'ilo_Latn',
    'ind_Latn',
    'isl_Latn',
    'ita_Latn',
    'jav_Latn',
    'jpn_Jpan',
    'kab_Latn',
    'kac_Latn',
    'kam_Latn',
    'kan_Knda',
    'kas_Arab',
    'kas_Deva',
    'kat_Geor',
    'kaz_Cyrl',
    'kbp_Latn',
    'kea_Latn',
    'khk_Cyrl',
    'khm_Khmr',
    'kik_Latn',
    'kin_Latn',
    'kir_Cyrl',
    'kmb_Latn',
    'kmr_Latn',
    'knc_Arab',
    'knc_Latn',
    'kon_Latn',
    'kor_Hang',
    'lao_Laoo',
    'lij_Latn',
    'lim_Latn',
    'lin_Latn',
    'lit_Latn',
    'lmo_Latn',
    'ltg_Latn',
    'ltz_Latn',
    'lua_Latn',
    'lug_Latn',
    'luo_Latn',
    'lus_Latn',
    'lvs_Latn',
    'mag_Deva',
    'mai_Deva',
    'mal_Mlym',
    'mar_Deva',
    'min_Arab',
    'min_Latn',
    'mkd_Cyrl',
    'mlt_Latn',
    'mni_Beng',
    'mos_Latn',
    'mri_Latn',
    'mya_Mymr',
    'nld_Latn',
    'nno_Latn',
    'nob_Latn',
    'npi_Deva',
    'nso_Latn',
    'nus_Latn',
    'nya_Latn',
    'oci_Latn',
    'ory_Orya',
    'pag_Latn',
    'pan_Guru',
    'pap_Latn',
    'pbt_Arab',
    'pes_Arab',
    'plt_Latn',
    'pol_Latn',
    'por_Latn',
    'prs_Arab',
    'quy_Latn',
    'ron_Latn',
    'run_Latn',
    'rus_Cyrl',
    'sag_Latn',
    'san_Deva',
    'sat_Olck',
    'scn_Latn',
    'shn_Mymr',
    'sin_Sinh',
    'slk_Latn',
    'slv_Latn',
    'smo_Latn',
    'sna_Latn',
    'snd_Arab',
    'som_Latn',
    'sot_Latn',
    'spa_Latn',
    'srd_Latn',
    'srp_Cyrl',
    'ssw_Latn',
    'sun_Latn',
    'swe_Latn',
    'swh_Latn',
    'szl_Latn',
    'tam_Taml',
    'taq_Latn',
    'taq_Tfng',
    'tat_Cyrl',
    'tel_Telu',
    'tgk_Cyrl',
    'tgl_Latn',
    'tha_Thai',
    'tir_Ethi',
    'tpi_Latn',
    'tsn_Latn',
    'tso_Latn',
    'tuk_Latn',
    'tum_Latn',
    'tur_Latn',
    'twi_Latn',
    'tzm_Tfng',
    'uig_Arab',
    'ukr_Cyrl',
    'umb_Latn',
    'urd_Arab',
    'uzn_Latn',
    'vec_Latn',
    'vie_Latn',
    'war_Latn',
    'wol_Latn',
    'xho_Latn',
    'ydd_Hebr',
    'yor_Latn',
    'yue_Hant',
    'zho_Hans',
    'zho_Hant',
}

ISO_TO_FLORES = {
    'ace': 'ace_Latn',
    'acm': 'acm_Arab',
    'acq': 'acq_Arab',
    'aeb': 'aeb_Arab',
    'af': 'afr_Latn',
    'afr': 'afr_Latn',
    'ajp': 'ajp_Arab',
    'aka': 'aka_Latn',
    'als': 'als_Latn',
    'amh': 'amh_Ethi',
    'apc': 'apc_Arab',
    'arb': 'arb_Latn',
    'ars': 'ars_Arab',
    'ary': 'ary_Arab',
    'arz': 'arz_Arab',
    'asm': 'asm_Beng',
    'ast': 'ast_Latn',
    'awa': 'awa_Deva',
    'ayr': 'ayr_Latn',
    'azb': 'azb_Arab',
    'azj': 'azj_Latn',
    'bak': 'bak_Cyrl',
    'bam': 'bam_Latn',
    'ban': 'ban_Latn',
    'be': 'bel_Cyrl',
    'bel': 'bel_Cyrl',
    'bem': 'bem_Latn',
    'ben': 'ben_Beng',
    'bg': 'bul_Cyrl',
    'bho': 'bho_Deva',
    'bjn': 'bjn_Latn',
    'bn': 'ben_Beng',
    'bod': 'bod_Tibt',
    'bos': 'bos_Latn',
    'bs': 'bos_Latn',
    'bug': 'bug_Latn',
    'bul': 'bul_Cyrl',
    'ca': 'cat_Latn',
    'cat': 'cat_Latn',
    'ceb': 'ceb_Latn',
    'ces': 'ces_Latn',
    'cjk': 'cjk_Latn',
    'ckb': 'ckb_Arab',
    'crh': 'crh_Latn',
    'cs': 'ces_Latn',
    'cy': 'cym_Latn',
    'cym': 'cym_Latn',
    'da': 'dan_Latn',
    'dan': 'dan_Latn',
    'de': 'deu_Latn',
    'deu': 'deu_Latn',
    'dik': 'dik_Latn',
    'dyu': 'dyu_Latn',
    'dzo': 'dzo_Tibt',
    'el': 'ell_Grek',
    'ell': 'ell_Grek',
    'en': 'eng_Latn',
    'eng': 'eng_Latn',
    'eo': 'epo_Latn',
    'epo': 'epo_Latn',
    'es': 'spa_Latn',
    'est': 'est_Latn',
    'et': 'est_Latn',
    'eu': 'eus_Latn',
    'eus': 'eus_Latn',
    'ewe': 'ewe_Latn',
    'fao': 'fao_Latn',
    'fi': 'fin_Latn',
    'fij': 'fij_Latn',
    'fin': 'fin_Latn',
    'fon': 'fon_Latn',
    'fr': 'fra_Latn',
    'fra': 'fra_Latn',
    'fur': 'fur_Latn',
    'fuv': 'fuv_Latn',
    'ga': 'gle_Latn',
    'gaz': 'gaz_Latn',
    'gla': 'gla_Latn',
    'gle': 'gle_Latn',
    'glg': 'glg_Latn',
    'grn': 'grn_Latn',
    'gu': 'guj_Gujr',
    'guj': 'guj_Gujr',
    'hat': 'hat_Latn',
    'hau': 'hau_Latn',
    'he': 'heb_Hebr',
    'heb': 'heb_Hebr',
    'hi': 'hin_Deva',
    'hin': 'hin_Deva',
    'hne': 'hne_Deva',
    'hr': 'hrv_Latn',
    'hrv': 'hrv_Latn',
    'hu': 'hun_Latn',
    'hun': 'hun_Latn',
    'hy': 'hye_Armn',
    'hye': 'hye_Armn',
    'ibo': 'ibo_Latn',
    'id': 'ind_Latn',
    'ilo': 'ilo_Latn',
    'ind': 'ind_Latn',
    'is': 'isl_Latn',
    'isl': 'isl_Latn',
    'it': 'ita_Latn',
    'ita': 'ita_Latn',
    'ja': 'jpn_Jpan',
    'jav': 'jav_Latn',
    'jpn': 'jpn_Jpan',
    'ka': 'kat_Geor',
    'kab': 'kab_Latn',
    'kac': 'kac_Latn',
    'kam': 'kam_Latn',
    'kan': 'kan_Knda',
    'kas': 'kas_Arab',
    'kat': 'kat_Geor',
    'kaz': 'kaz_Cyrl',
    'kbp': 'kbp_Latn',
    'kea': 'kea_Latn',
    'khk': 'khk_Cyrl',
    'khm': 'khm_Khmr',
    'kik': 'kik_Latn',
    'kin': 'kin_Latn',
    'kir': 'kir_Cyrl',
    'kk': 'kaz_Cyrl',
    'kmb': 'kmb_Latn',
    'kmr': 'kmr_Latn',
    'knc': 'knc_Latn',
    'ko': 'kor_Hang',
    'kon': 'kon_Latn',
    'kor': 'kor_Hang',
    'lao': 'lao_Laoo',
    'lg': 'lug_Latn',
    'lij': 'lij_Latn',
    'lim': 'lim_Latn',
    'lin': 'lin_Latn',
    'lit': 'lit_Latn',
    'lmo': 'lmo_Latn',
    'lt': 'lit_Latn',
    'ltg': 'ltg_Latn',
    'ltz': 'ltz_Latn',
    'lua': 'lua_Latn',
    'lug': 'lug_Latn',
    'luo': 'luo_Latn',
    'lus': 'lus_Latn',
    'lvs': 'lvs_Latn',
    'mag': 'mag_Deva',
    'mai': 'mai_Deva',
    'mal': 'mal_Mlym',
    'mar': 'mar_Deva',
    'mi': 'mri_Latn',
    'min': 'min_Latn',
    'mk': 'mkd_Cyrl',
    'mkd': 'mkd_Cyrl',
    'mlt': 'mlt_Latn',
    'mni': 'mni_Beng',
    'mos': 'mos_Latn',
    'mr': 'mar_Deva',
    'mri': 'mri_Latn',
    'mya': 'mya_Mymr',
    'nb': 'nob_Latn',
    'nl': 'nld_Latn',
    'nld': 'nld_Latn',
    'nn': 'nno_Latn',
    'nno': 'nno_Latn',
    'nob': 'nob_Latn',
    'npi': 'npi_Deva',
    'nso': 'nso_Latn',
    'nus': 'nus_Latn',
    'nya': 'nya_Latn',
    'oci': 'oci_Latn',
    'ory': 'ory_Orya',
    'pa': 'pan_Guru',
    'pag': 'pag_Latn',
    'pan': 'pan_Guru',
    'pap': 'pap_Latn',
    'pbt': 'pbt_Arab',
    'pes': 'pes_Arab',
    'pl': 'pol_Latn',
    'plt': 'plt_Latn',
    'pol': 'pol_Latn',
    'por': 'por_Latn',
    'prs': 'prs_Arab',
    'pt': 'por_Latn',
    'quy': 'quy_Latn',
    'ro': 'ron_Latn',
    'ron': 'ron_Latn',
    'ru': 'rus_Cyrl',
    'run': 'run_Latn',
    'rus': 'rus_Cyrl',
    'sag': 'sag_Latn',
    'san': 'san_Deva',
    'sat': 'sat_Olck',
    'scn': 'scn_Latn',
    'shn': 'shn_Mymr',
    'sin': 'sin_Sinh',
    'sk': 'slk_Latn',
    'sl': 'slv_Latn',
    'slk': 'slk_Latn',
    'slv': 'slv_Latn',
    'smo': 'smo_Latn',
    'sn': 'sna_Latn',
    'sna': 'sna_Latn',
    'snd': 'snd_Arab',
    'so': 'som_Latn',
    'som': 'som_Latn',
    'sot': 'sot_Latn',
    'spa': 'spa_Latn',
    'sr': 'srp_Cyrl',
    'srd': 'srd_Latn',
    'srp': 'srp_Cyrl',
    'ssw': 'ssw_Latn',
    'st': 'sot_Latn',
    'sun': 'sun_Latn',
    'sv': 'swe_Latn',
    'swe': 'swe_Latn',
    'swh': 'swh_Latn',
    'szl': 'szl_Latn',
    'ta': 'tam_Taml',
    'tam': 'tam_Taml',
    'taq': 'taq_Latn',
    'tat': 'tat_Cyrl',
    'te': 'tel_Telu',
    'tel': 'tel_Telu',
    'tgk': 'tgk_Cyrl',
    'tgl': 'tgl_Latn',
    'th': 'tha_Thai',
    'tha': 'tha_Thai',
    'tir': 'tir_Ethi',
    'tl': 'tgl_Latn',
    'tn': 'tsn_Latn',
    'tpi': 'tpi_Latn',
    'tr': 'tur_Latn',
    'ts': 'tso_Latn',
    'tsn': 'tsn_Latn',
    'tso': 'tso_Latn',
    'tuk': 'tuk_Latn',
    'tum': 'tum_Latn',
    'tur': 'tur_Latn',
    'twi': 'twi_Latn',
    'tzm': 'tzm_Tfng',
    'uig': 'uig_Arab',
    'uk': 'ukr_Cyrl',
    'ukr': 'ukr_Cyrl',
    'umb': 'umb_Latn',
    'ur': 'urd_Arab',
    'urd': 'urd_Arab',
    'uzn': 'uzn_Latn',
    'vec': 'vec_Latn',
    'vi': 'vie_Latn',
    'vie': 'vie_Latn',
    'war': 'war_Latn',
    'wol': 'wol_Latn',
    'xh': 'xho_Latn',
    'xho': 'xho_Latn',
    'ydd': 'ydd_Hebr',
    'yo': 'yor_Latn',
    'yor': 'yor_Latn',
    'yue': 'yue_Hant',
    'zh': 'zho_Hans',
    'zho': 'zho_Hans',
}

FLORES_TO_ISO = {
    'ace_Arab': 'ace',
    'ace_Latn': 'ace',
    'acm_Arab': 'acm',
    'acq_Arab': 'acq',
    'aeb_Arab': 'aeb',
    'afr_Latn': 'af',
    'ajp_Arab': 'ajp',
    'aka_Latn': 'aka',
    'als_Latn': 'als',
    'amh_Ethi': 'amh',
    'apc_Arab': 'apc',
    'arb_Arab': 'arb',
    'arb_Latn': 'arb',
    'ars_Arab': 'ars',
    'ary_Arab': 'ary',
    'arz_Arab': 'arz',
    'asm_Beng': 'asm',
    'ast_Latn': 'ast',
    'awa_Deva': 'awa',
    'ayr_Latn': 'ayr',
    'azb_Arab': 'azb',
    'azj_Latn': 'azj',
    'bak_Cyrl': 'bak',
    'bam_Latn': 'bam',
    'ban_Latn': 'ban',
    'bel_Cyrl': 'be',
    'bem_Latn': 'bem',
    'ben_Beng': 'bn',
    'bho_Deva': 'bho',
    'bjn_Arab': 'bjn',
    'bjn_Latn': 'bjn',
    'bod_Tibt': 'bod',
    'bos_Latn': 'bs',
    'bug_Latn': 'bug',
    'bul_Cyrl': 'bg',
    'cat_Latn': 'ca',
    'ceb_Latn': 'ceb',
    'ces_Latn': 'cs',
    'cjk_Latn': 'cjk',
    'ckb_Arab': 'ckb',
    'crh_Latn': 'crh',
    'cym_Latn': 'cy',
    'dan_Latn': 'da',
    'deu_Latn': 'de',
    'dik_Latn': 'dik',
    'dyu_Latn': 'dyu',
    'dzo_Tibt': 'dzo',
    'ell_Grek': 'el',
    'eng_Latn': 'en',
    'epo_Latn': 'eo',
    'est_Latn': 'et',
    'eus_Latn': 'eu',
    'ewe_Latn': 'ewe',
    'fao_Latn': 'fao',
    'fij_Latn': 'fij',
    'fin_Latn': 'fi',
    'fon_Latn': 'fon',
    'fra_Latn': 'fr',
    'fur_Latn': 'fur',
    'fuv_Latn': 'fuv',
    'gaz_Latn': 'gaz',
    'gla_Latn': 'gla',
    'gle_Latn': 'ga',
    'glg_Latn': 'glg',
    'grn_Latn': 'grn',
    'guj_Gujr': 'gu',
    'hat_Latn': 'hat',
    'hau_Latn': 'hau',
    'heb_Hebr': 'he',
    'hin_Deva': 'hi',
    'hne_Deva': 'hne',
    'hrv_Latn': 'hr',
    'hun_Latn': 'hu',
    'hye_Armn': 'hy',
    'ibo_Latn': 'ibo',
    'ilo_Latn': 'ilo',
    'ind_Latn': 'id',
    'isl_Latn': 'is',
    'ita_Latn': 'it',
    'jav_Latn': 'jav',
    'jpn_Jpan': 'ja',
    'kab_Latn': 'kab',
    'kac_Latn': 'kac',
    'kam_Latn': 'kam',
    'kan_Knda': 'kan',
    'kas_Arab': 'kas',
    'kas_Deva': 'kas',
    'kat_Geor': 'ka',
    'kaz_Cyrl': 'kk',
    'kbp_Latn': 'kbp',
    'kea_Latn': 'kea',
    'khk_Cyrl': 'khk',
    'khm_Khmr': 'khm',
    'kik_Latn': 'kik',
    'kin_Latn': 'kin',
    'kir_Cyrl': 'kir',
    'kmb_Latn': 'kmb',
    'kmr_Latn': 'kmr',
    'knc_Arab': 'knc',
    'knc_Latn': 'knc',
    'kon_Latn': 'kon',
    'kor_Hang': 'ko',
    'lao_Laoo': 'lao',
    'lij_Latn': 'lij',
    'lim_Latn': 'lim',
    'lin_Latn': 'lin',
    'lit_Latn': 'lt',
    'lmo_Latn': 'lmo',
    'ltg_Latn': 'ltg',
    'ltz_Latn': 'ltz',
    'lua_Latn': 'lua',
    'lug_Latn': 'lg',
    'luo_Latn': 'luo',
    'lus_Latn': 'lus',
    'lvs_Latn': 'lvs',
    'mag_Deva': 'mag',
    'mai_Deva': 'mai',
    'mal_Mlym': 'mal',
    'mar_Deva': 'mr',
    'min_Arab': 'min',
    'min_Latn': 'min',
    'mkd_Cyrl': 'mk',
    'mlt_Latn': 'mlt',
    'mni_Beng': 'mni',
    'mos_Latn': 'mos',
    'mri_Latn': 'mi',
    'mya_Mymr': 'mya',
    'nld_Latn': 'nl',
    'nno_Latn': 'nn',
    'nob_Latn': 'nb',
    'npi_Deva': 'npi',
    'nso_Latn': 'nso',
    'nus_Latn': 'nus',
    'nya_Latn': 'nya',
    'oci_Latn': 'oci',
    'ory_Orya': 'ory',
    'pag_Latn': 'pag',
    'pan_Guru': 'pa',
    'pap_Latn': 'pap',
    'pbt_Arab': 'pbt',
    'pes_Arab': 'pes',
    'plt_Latn': 'plt',
    'pol_Latn': 'pl',
    'por_Latn': 'pt',
    'prs_Arab': 'prs',
    'quy_Latn': 'quy',
    'ron_Latn': 'ro',
    'run_Latn': 'run',
    'rus_Cyrl': 'ru',
    'sag_Latn': 'sag',
    'san_Deva': 'san',
    'sat_Olck': 'sat',
    'scn_Latn': 'scn',
    'shn_Mymr': 'shn',
    'sin_Sinh': 'sin',
    'slk_Latn': 'sk',
    'slv_Latn': 'sl',
    'smo_Latn': 'smo',
    'sna_Latn': 'sn',
    'snd_Arab': 'snd',
    'som_Latn': 'so',
    'sot_Latn': 'st',
    'spa_Latn': 'es',
    'srd_Latn': 'srd',
    'srp_Cyrl': 'sr',
    'ssw_Latn': 'ssw',
    'sun_Latn': 'sun',
    'swe_Latn': 'sv',
    'swh_Latn': 'swh',
    'szl_Latn': 'szl',
    'tam_Taml': 'ta',
    'taq_Latn': 'taq',
    'taq_Tfng': 'taq',
    'tat_Cyrl': 'tat',
    'tel_Telu': 'te',
    'tgk_Cyrl': 'tgk',
    'tgl_Latn': 'tl',
    'tha_Thai': 'th',
    'tir_Ethi': 'tir',
    'tpi_Latn': 'tpi',
    'tsn_Latn': 'tn',
    'tso_Latn': 'ts',
    'tuk_Latn': 'tuk',
    'tum_Latn': 'tum',
    'tur_Latn': 'tr',
    'twi_Latn': 'twi',
    'tzm_Tfng': 'tzm',
    'uig_Arab': 'uig',
    'ukr_Cyrl': 'uk',
    'umb_Latn': 'umb',
    'urd_Arab': 'ur',
    'uzn_Latn': 'uzn',
    'vec_Latn': 'vec',
    'vie_Latn': 'vi',
    'war_Latn': 'war',
    'wol_Latn': 'wol',
    'xho_Latn': 'xh',
    'ydd_Hebr': 'ydd',
    'yor_Latn': 'yo',
    'yue_Hant': 'yue',
    'zho_Hans': 'zh',
    'zho_Hant': 'zh',
}
